# Generated by Django 5.2.2 on 2025-06-08 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('general', 'General User'), ('admin', 'Administrator')], default='general', max_length=10),
        ),
    ]
