# Generated by Django 5.2.2 on 2025-06-07 08:17

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_add_user_relations'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('website', models.URLField(validators=[django.core.validators.URLValidator()])),
                ('industry', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=255)),
                ('contact_number', models.CharField(max_length=20)),
                ('verified', models.BooleanField(default=False)),
                ('about', models.TextField()),
                ('company_logo', models.URLField(validators=[django.core.validators.URLValidator()])),
                ('posted_jobs', models.JSONField(default=list)),
                ('user', models.OneToOneField(limit_choices_to={'role': 'company'}, on_delete=django.db.models.deletion.CASCADE, related_name='company_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college', models.CharField(max_length=255)),
                ('degree', models.CharField(max_length=100)),
                ('branch', models.CharField(max_length=100)),
                ('graduation_year', models.PositiveIntegerField()),
                ('skills', models.JSONField(default=list)),
                ('resume_link', models.URLField(validators=[django.core.validators.URLValidator()])),
                ('portfolio_link', models.URLField(blank=True, null=True, validators=[django.core.validators.URLValidator()])),
                ('linkedin', models.URLField(blank=True, null=True, validators=[django.core.validators.URLValidator()])),
                ('github', models.URLField(blank=True, null=True, validators=[django.core.validators.URLValidator()])),
                ('bio', models.TextField(blank=True)),
                ('applications', models.JSONField(default=list)),
                ('saved_posts', models.JSONField(default=list)),
                ('user', models.OneToOneField(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
