# Generated by Django 5.2.2 on 2025-06-08 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_companyprofile_studentprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='CompanyProfile',
        ),
        migrations.DeleteModel(
            name='StudentProfile',
        ),
    ]
