# Generated by Django 4.2.23 on 2025-06-15 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0002_remove_submission_submission_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='submission_file',
            field=models.FileField(blank=True, null=True, upload_to='submissions/', verbose_name='Submission File'),
        ),
    ]
